[package]

name = "rust_learning"
version = "0.0.1"
authors = [ "cyan <https://github.com/snipercy" ]

[[bin]]
name = "hello_world"
path = "src/hello_world.rs"

[[bin]]
name = "guess_num"
path = "src/guess_num.rs"

[dependencies]

rand = "0.3.0"
